apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: broboosted/mon-app-node:v1
          ports:
            - containerPort: 3000
          # Étape 4 : Injection des variables d'environnement
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_PASSWORD
          # Étape 3 : Montage du volume
          volumeMounts:
            - name: config-volume
              mountPath: /app/config/
      volumes:
        - name: config-volume
          configMap:
            name: app-config
